spring.datasource.url=jdbc:postgresql://ep-cold-darkness-aiziz7vu-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_avYw5rcRi9TW

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


spring.data.mongodb.uri=mongodb+srv://najib:najib2004@ecotrack.xrerfns.mongodb.net/ecotrack_media?appName=EcoTrack


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mednajibnaitkhouya@gmail.com
spring.mail.password=fnws dtdt zsis qtyq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.ai.ollama.chat.options.model=llama3.1:8b
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://integrate.api.nvidia.com
spring.ai.openai.chat.options.model=openai/gpt-oss-120b